import os
import json
import sys

# Define path relative to repository structure
script_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.dirname(script_dir)

# Path to the cloned ai-berkshire repository containing the skills
skills_dir = os.path.abspath(os.path.join(project_root, "..", "..", "my_app", "aiberkshir", "skills"))
if not os.path.exists(skills_dir):
    # Fallback to local check
    skills_dir = os.path.abspath(os.path.join(project_root, "skills"))

output_file = os.path.join(project_root, "src", "lib", "skillsData.ts")

if not os.path.exists(skills_dir):
    print(f"Error: Skills directory not found at {skills_dir}")
    sys.exit(1)

skills = []

for filename in os.listdir(skills_dir):
    if filename.endswith(".md"):
        filepath = os.path.join(skills_dir, filename)
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()
        
        lines = content.splitlines()
        title = filename[:-3] # fallback
        description = ""
        
        # Parse first heading as title
        for line in lines:
            if line.startswith("# "):
                title = line[2:].strip()
                break
        
        # Parse first few lines as description
        desc_lines = []
        started = False
        for line in lines:
            if line.startswith("# "):
                started = True
                continue
            if started:
                cleaned = line.strip()
                if cleaned:
                    desc_lines.append(cleaned)
                    if len(desc_lines) >= 3:
                        break
        description = " ".join(desc_lines)[:150] + "..." if desc_lines else "AI Berkshire investment research skill."
        
        skills.append({
            "id": filename[:-3],
            "title": title,
            "description": description,
            "prompt": content
        })

# Write TypeScript file
ts_content = f"""// This file is auto-generated by compile_skills.py. Do not edit manually.
export interface ResearchSkill {{
  id: string;
  title: string;
  description: string;
  prompt: string;
}}

export const RESEARCH_SKILLS: ResearchSkill[] = {json.dumps(skills, indent=2, ensure_ascii=False)};
"""

os.makedirs(os.path.dirname(output_file), exist_ok=True)

with open(output_file, "w", encoding="utf-8") as f:
    f.write(ts_content)

print(f"Successfully compiled {len(skills)} skills into {output_file}")
